<a href="https://colab.research.google.com/github/geminicopilotgpt/GenAI/blob/main/NLP4Dec2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
print("Hello World")

Hello World


In [4]:
### Word and sentence embeddeding

In [ ]:
#OHE - One hot encoding

#Vocabulary - unique words/distinct words

"""
Pros:-
1.Easy to implement

Cons:-
1.Sparse matrix
[too many zeros in the given matrix]


2.OOV[out of vocubulary]

3.No fix dimension issue
[rows and column different]

"""

In [ ]:
#Vector - numerical representation of the text or set of numbers

#BOW
"""
BOW - Bag of words - 2018,2019
BOW is a frequency based method

Frequency - occurence of the words

"""


In [ ]:
"""
Advantage:-
1.Simple


Disadvantage:-
1.Sparcity
zeros,ones
calculate the frequency of words only, not make any sort of relations here between this words and all
2.not capturing semantic info
OOV - Out of vocabulary


"""

In [ ]:
#N-grams
"""
N=1 => Single word[unigran]

N=2 => Pair of 2 words[bigram]

N=3 => Pair of 3 words[trigram]
.
.
.
.
.
Popular till 2018, 2019

unigram(BOW - Bag of words)
bigram(2 words)

Pair of the words => context of the data = retain the information = capture the semantic meaning


Create vocabulary[unique words] from data

{People, watch, cricket, give, comment}

bigram -> doublewords
{(People, watch),(watch,cricket),(cricket,give),(give,comment)}


people watch	1
people cricket	1
people give	1
people comment	1
watch cricket	1
watch give	1
watch comment	1
cricket give	1
cricket comment	1
give comment	1


Keep 3 word pair - trigran, quadgram, pentagram, hexagram

Identify the vector by creating pair


Advantage:-
1.simple to use
2.sustain context(pair)

Disadvantage:-
1.sparse matrix(0,1 value coming so many times)
2.oov(out of vocabulary issue, new words - old vocabulary won't work)
"""

In [5]:
#Encoding

import pandas as pd



In [7]:
data=pd.DataFrame({"text":["people watch cricket","cricket watch cricket","people give comment","cricket give comment"],"output":[1,1,0,0]})

In [8]:
data

text  output
0   people watch cricket       1
1  cricket watch cricket       1
2    people give comment       0
3   cricket give comment       0

In [35]:
# pip install scikit-learn

In [36]:
#CountVectorizer - https://scikit-learn.org/1.5/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
BOW=CountVectorizer()

In [13]:
data["text"]

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

In [14]:
document_matrix=BOW.fit_transform(data["text"])

In [15]:
document_matrix

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [17]:
# Alphabatical sequence

In [18]:
BOW.vocabulary_

{'people': 3, 'watch': 4, 'cricket': 1, 'give': 2, 'comment': 0}

In [19]:
document_matrix[0].toarray()

array([[0, 1, 0, 1, 1]])

In [20]:
document_matrix[1].toarray()

array([[0, 2, 0, 0, 1]])

In [21]:
document_matrix[2].toarray()

array([[1, 0, 1, 1, 0]])

In [22]:
document_matrix[3].toarray()

array([[1, 1, 1, 0, 0]])

In [23]:
"""implement OHE for the below data using ANY library(for example numpy, pandas, tf, pytorch etc...)
after completeing this tag me and krish sir and send your solution in group chat
in next class i will give you the quick overview of it
"""

'implement OHE for the below data using ANY library(for example numpy, pandas, tf, pytorch etc...)\nafter completeing this tag me and krish sir and send your solution in group chat\nin next class i will give you the quick overview of it\n'

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

In [25]:
bigram=CountVectorizer(ngram_range=(2,2))

In [26]:
bigramvocab=bigram.fit_transform(data["text"])

In [27]:
data["text"]

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

In [28]:
bigram.vocabulary_

{'people watch': 4,
 'watch cricket': 5,
 'cricket watch': 1,
 'people give': 3,
 'give comment': 2,
 'cricket give': 0}

In [29]:
trigram=CountVectorizer(ngram_range=(3,3))

In [30]:
trigramvocab=trigram.fit_transform(data["text"])

In [31]:
trigram.vocabulary_

{'people watch cricket': 3,
 'cricket watch cricket': 1,
 'people give comment': 2,
 'cricket give comment': 0}

In [32]:
mix=CountVectorizer(ngram_range=(1,3))

In [33]:
mix_vocab=mix.fit_transform(data["text"])

In [34]:
mix.vocabulary_

{'people': 8,
 'watch': 13,
 'cricket': 1,
 'people watch': 11,
 'watch cricket': 14,
 'people watch cricket': 12,
 'cricket watch': 4,
 'cricket watch cricket': 5,
 'give': 6,
 'comment': 0,
 'people give': 9,
 'give comment': 7,
 'people give comment': 10,
 'cricket give': 2,
 'cricket give comment': 3}